### ISSUE TITLE
Upgrade to version 2 spec

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/ocaml-test-runner#13]
If possible, this test runner should be updated to version 2 of the [test runner interface specification](https://github.com/exercism/docs/blob/main/building/tooling/test-runners/interface.md).

The version 2 spec differs from version 1 in that the `results.json` file contains detailed information on individual tests.
This information includes things like:

- The test status (passing/failing)
- The error message (if failing)
- The test code that was used to run the test

You are completely free on how you want to extract the test code, either via the AST or via finding the test code in the source code text via string manipulation. 

Let me know if there are any questions.

**Comment by tautologico** [comment]
In order to test the updated test runner, I have to create the expected output files and run the tests again, correct? Looking at the expected output for the Rust test runner, it seems to me that the code that was used to run the test is not present. Is this a limitation of this specific runner?

**Comment by tautologico** [comment]
I see the spec says the code SHOULD be present for practice exercises and MUST be present for concept exercises, so this explain the Rust runner output. I will try to output the test code for all exercises.

**Comment by ErikSchierboom** [comment]
> In order to test the updated test runner, I have to create the expected output files and run the tests again, correct?

Yep. You update the `expected-results.json` files and run `./bin/run-tests-in-docker.sh`. Alternatively, you make the changes in the code, run `./bin/run-tests-in-docker.sh` and then copy the generated `results.json` files to `expected-results.json` files. Note: this only really works if your code works as intended :) But it can be a nice starting point without having to manually add all tests.

> Looking at the expected output for the Rust test runner, it seems to me that the code that was used to run the test is not present. Is this a limitation of this specific runner?

Likely. There are lots of other test runners that do support it, like the C#/F#/Elixir test runners.

> I will try to output the test code for all exercises.

Usually, whether the exercise is a concept or practice exercise doesn't really matter anyway.

**Comment by georgyo** [comment]
With #35 merged, I think we are officially version 2! :tada: 

Great work @tautologico !
