### ISSUE TITLE
Runner version mismatch (4.07.0 / 4.12.0)

### ISSUE THREAD

**Issue by maximemenager** [exercism/ocaml-test-runner#17]
Hi,

My tests pass locally, but fail online on the Difference Of Squares Ocaml track exercise (https://exercism.org/tracks/ocaml/exercises/difference-of-squares)

It seems that the runner uses a 4.07.0 Ocaml version (see here: https://github.com/exercism/ocaml-test-runner/blob/main/Dockerfile#L2), but the latest version is 4.12.0 at this time.

Here is a screenshot of the online issue, followed by a codeblock of my local investigation.

![image](https://user-images.githubusercontent.com/43468959/134166564-172f5af4-f39d-41fa-aa0b-6049a142f067.png)

```bash
➜  difference-of-squares git:(master) ✗ asdf local ocaml 4.07.0
➜  difference-of-squares git:(master) ✗ make                   
dune clean
dune runtest
File "difference_of_squares.ml", line 6, characters 12-22:
Error: Unbound value Seq.unfold
make: *** [Makefile:4 : test] Erreur 1
➜  difference-of-squares git:(master) ✗ asdf local ocaml 4.12.0
➜  difference-of-squares git:(master) ✗ make                   
dune clean
dune runtest
        test alias runtest
.........
Ran: 9 tests in: 0.10 seconds.
OK
➜  difference-of-squares git:(master) ✗ 
```

**Comment by ErikSchierboom** [comment]
Thanks for reporting! I'm working on fixing this.

**Comment by ErikSchierboom** [comment]
@maximemenager This should be fixed once #18 is merged. If you are interested, would you be willing to add a test case to the test runner tests at https://github.com/exercism/ocaml-test-runner/tree/main/tests that would fail if run on an older OCaml version?

**Comment by ErikSchierboom** [comment]
@maximemenager I've just successfully been able to run the tests. Could you check if the difference-of-squares solution now works as expected?

![image](https://user-images.githubusercontent.com/135246/134297036-e9dad7d3-4193-48c4-9ca9-2a349696477d.png)

**Comment by maximemenager** [comment]
Yep, it's perfect !

![image](https://user-images.githubusercontent.com/43468959/134299900-05f5ba31-ae2b-4b91-823d-f1a12d781306.png)

I'll try to add a test to the runner tests in the week. On which versions of OCaml the tests are executed ?

**Comment by ErikSchierboom** [comment]
The test runner uses 4.14.
